[theme]
name = "gruvbox-dark"

[icons]
name = "awesome"

interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "updated"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "networkmanager"
on_click = "networkmanager_dmenu"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "cpu"
interval = 0.7

[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
